name: Testing various Actions things

on:
  workflow_dispatch:
  push:

jobs:
  test-find-codeql:
    runs-on: ubuntu-latest
    steps:
      - name: Look for CodeQL in the Actions tool cache
        shell: bash -ex {0}
        run: |
          VERSION="$(find "${{ runner.tool_cache }}/CodeQL" -maxdepth 1 -mindepth 1 -type d -print \
            | sort \
            | tail -n 1 \
            | tr -d '\n')"
          echo $VERSION
          if [ -z "$VERSION" ]
          then
            echo "$VERSION/x64/codeql" >> $GITHUB_PATH
          else
            gh extensions install github/gh-codeql
            gh codeql download
            gh codeql install-stub
          fi
          echo "Using CodeQL at $(which codeql)"
