name: Code Scanning alert

on:
  repository_dispatch:
    types:
      - code_scanning_alert

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  user-dismissed-an-alert:
    name: User dismissed an alert
    if: |
      github.event.client_payload.action == 'closed_by_user' &&
      github.event.client_payload.alert.state == 'dismissed'
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh api \
            --method PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.event.client_payload.repository.owner.login }}/${{ github.event.client_payload.repository.name }}/code-scanning/alerts/${{ github.event.client_payload.alert.number }} \
            -f state='open'
